### PR TITLE
Parity Support

### PR DESCRIPTION
**Pull request by tagomaru**
This PR is for parity support.
It needs to change the repos `priv-testnet`, `orchestration`, `polyswarmd`, and `contractor` as well.

### CODE REVIEW

**Comment by myhndl** [comment]
Note: this increases a timeout (presumably Parity takes longer to become available) and generalizes a log message to apply to both Geth and Ethereum.

**Comment by tagomaru** [comment]
Hi @myhndl 
Indeed you understanding is correct.

**Comment by tagomaru** [comment]
@Rizato 
Thx, I fixed!

**Comment by myhndl** [comment]
@Rizato please merge at will

**Pull request merged**
